name: GitHub Action for pytest
  # You may pin to the exact commit or the version.
  # uses: cclauss/GitHub-Action-for-pytest@5863d02de95f37516a732802fa6257dfdf93e54c
uses: cclauss/GitHub-Action-for-pytest@0.5.0
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install  pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      name: Run test
      - pytest
